[package]
name = "alina-poster"
version = "0.0.1"
entrypoint = "alina-poster.typ"
authors = ["Jérémy La Scala"]
license = "CC-BY-SA 4.0 International"
description = "Poster template for typst"
repository = "https://github.com/swouf/alina-poster-template"
exclude = ["README.md"]